#ifndef DLLPINCODECOMPONENT_GLOBAL_H
#define DLLPINCODECOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLPINCODECOMPONENT_LIBRARY)
#  define DLLPINCODECOMPONENT_EXPORT Q_DECL_EXPORT
#else
#  define DLLPINCODECOMPONENT_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLPINCODECOMPONENT_GLOBAL_H
